-- liquibase formatted sql

-- changeset Caveri:1

CREATE TABLE comment
(
    pk         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at bigint      NOT NULL,
    text       VARCHAR(64) NOT NULL,
    ad_id      INTEGER     NOT NULL,
    user_id    INTEGER     NOT NULL,

    FOREIGN KEY (ad_id) REFERENCES ad (ad_id),
    FOREIGN KEY (user_id) REFERENCES users (user_id)
);